spring.application.name=proyecto-integrador-poo
server.port=8080

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=America/Argentina/Buenos_Aires

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never